title: Dark Poole
url: https://getpoole.com
paginate: 1
baseurl: ""
permalink: pretty

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Devansh Singh
  url: https://github.com/Devansh3712
  email: devanshamity@gmail.com

version: 3.0.0
